[project]
name = "unifi-stock-check"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = ["requests>=2.32.3", "ruff>=0.14.10"]

[tool.ruff.lint]
select = ["ALL"]
# Allow prints, broad exception catch, and resolve incompatible docstring rules
ignore = ["T201", "BLE001", "D203", "D213"]
